import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";
import AuthContext from "@/components/AuthContext";
import { Header } from "@/components/layout/Header";
import { BottomNavigate } from "@/components/layout/BottomNavigate";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <Provider>
            <Header />
            <main className="h-[90vh]">{children}</main>
            <BottomNavigate />
          </Provider>
        </AuthContext>
      </body>
    </html>
  );
}
