import AuthContext from "@/components/AuthContext";
import { BottomNavigate } from "@/components/layout/BottomNavigate";
import { Header } from "@/components/layout/Header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import { Provider } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = headers();
  const pathname = headersList.get("x-invoke-path");
  const isNotLoginPage = pathname !== "/";

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <Provider>
            {isNotLoginPage && <Header />}
            <main className="h-[90vh]">{children}</main>
            {isNotLoginPage && <BottomNavigate />}
          </Provider>
        </AuthContext>
        <div id="portal" />
      </body>
    </html>
  );
}
